version: '3'

services:
  api-fastapi:
    image: python:3.11
    ports:
      - "80:80"
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "main.py"]
    networks:
      - fastapi-network

    entrypoint: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             exec python main.py"
    


networks:
  fastapi-network:
    driver: bridge

