version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["python", "main.py"]
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge
