version: '3'

services:
  api-fastapi:
    image: python:3.11
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["python", "main.py"]
    networks:
      - fastapi-network
    


networks:
  fastapi-network:
    driver: bridge

