name: CI/CD

on:
    push:
        branches:
        - main

jobs:
    deploy:
        name: Deploy to Iart Data Server
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2
    

        - name: Deploy to Iart Data Server
          uses: appleboy/ssh-action@v1.0.3
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              sudo rm -rf iart_data_port_upload
              git clone git@github.com:hoangks5/iart_data_port_upload.git
              cd iart_data_port_upload
              echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" > .env
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
              echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
              echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
              echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
              echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
              echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> .env
              
              docker compose down --volumes
              docker compose up -d
            