name: CI/CD

on:
    push:
        branches:
        - main

jobs:
    deploy:
        name: Deploy to Iart Data Server
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Install SSH Client 🔑
          uses: webfactory/ssh-agent@v0.7.0
          with:
            ssh-private-key: ${{ secrets.DEPLOY_KEY }}


        - name: Deploy to Iart Data Server 🚀
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            BASE_BRANCH: main
            BRANCH: main
            FOLDER: .
            CLEAN: true
            SSH: true
            '