name: CI/CD

on:
    push:
        branches:
        - main

jobs:
    deploy:
        name: Deploy to Iart Data Server
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2
    

        - name: Deploy to Iart Data Server
          uses: appleboy/ssh-action@v1.0.3
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              rm -rf iart_data_port_upload
              git clone git@github.com:hoangks5/iart_data_port_upload.git
              cd iart_data_port_upload
              docker-compose up -d
            