name: CI/CD

on:
    push:
        branches:
        - main

jobs:
    deploy:
        name: Deploy to Iart Data Server
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            ssh-key: ${{ secrets.DEPLOY_KEY }}
            repository: hoangks5/iart_data_port_upload

        - name: Deploy to Iart Data Server
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

          run: |
            mkdir -p ~/.ssh/
            echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            ssh -i ~/.ssh/id_rsa $SSH_USERNAME@$SSH_HOST '
                rm -rf iart_data_port_upload
                git clone git@github.com:hoangks5/iart_data_port_upload.git
                '
            