name: CI/CD

on:
    push:
        branches:
        - main

jobs:
    deploy:
        name: Deploy to Iart Data Server
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Deploy to Iart Data Server
          uses: uses: appleboy/ssh-action@v1.0.3
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              whoami
              ls -al
            